let stopBtn = document.getElementById("stop")
        let startBtn = document.getElementById("start")
        let resetBtn = document.getElementById("reset")

        let display = document.getElementById("display")

        startBtn.addEventListener("click",watchStart)
        stopBtn.addEventListener("click",watchStop)
        resetBtn.addEventListener("click",watchReset)

        let timer = null;

           let mins = 0;
           let secs = 0;
           let hrs = 0

        function stopwatch(){
            secs+=1
             if (secs==60) {
                 secs=0
                 mins+=1
             }
             if (mins==60) {
                 mins=0
                 hrs+=1
             }

             let h = hrs < 10 ? "0"+hrs : hrs
             let m = mins < 10 ? "0"+mins : mins
             let s = secs < 10 ? "0"+secs : secs

             display.textContent= `${h}:${m}:${s}`
        }
        function watchStart(){
            if (timer!==null) {
                clearInterval(timer)
            }
            timer= setInterval(stopwatch,1000);
            
        }
        function watchStop(){
            clearInterval(timer);
        }
        function watchReset(){
            clearInterval(timer);
            mins=0
            secs=0
            hrs=0
            display.textContent= `00:00:00`
        }

//note timer functions in js are:
// setTimeout() and clearTimeout
// setInterval and clearInterval
// remember to collect the id generated by the sets to make the clear work
        